name: inspire
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.5.4

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.5
  flutter_launcher_icons: ^0.10.0
  animated_splash_screen: ^1.3.0
  google_fonts: ^3.0.1
  dots_indicator: ^2.1.0
  carousel_slider: ^4.1.1
  mask_text_input_formatter: ^2.4.0
  anchor_scroll_controller: ^0.4.1
  dotted_border: ^2.0.0+2
#  audioplayers_darwin: ^1.0.3
  audioplayers: ^1.1.0
  blurrycontainer: ^1.0.2
  just_audio: ^0.9.30
  percent_indicator: ^4.2.2
  animated_text_kit: ^4.2.2
  dio: ^4.0.6
  get_storage: ^2.0.3
  oktoast: ^3.3.1
  intl: ^0.17.0
  table_calendar: ^3.0.8
#  path_provider: ^2.0.11
#  open_file: ^2.1.1
  better_open_file: ^3.6.4
  image_picker: ^0.8.6
  skeletons: ^0.0.3
  photo_view: ^0.14.0
#  vimeoplayer_trinity: ^0.2.3
#  vimeo_player_flutter: ^0.0.3+2
#  pod_player: ^0.1.0
  vimeo_video_player: ^0.0.6
  flick_video_player: ^0.5.0
  video_player: ^2.4.7
#  icons_launcher: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
